### Vulnerable Web Network ###

version: '2.13.0'

services:

  kali:
    build: ./kali
    container_name: docker-kali
    hostname: kali
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    tty: true
    networks:
      vulnet:
        ipv4_address: 10.20.0.200
    volumes: 
 #    - /Users/em0ral/lab/python:/code-python
 #    - /Users/em0ral/lab/golang:/code-golang
      - /Users/em0ral/lab/docker/kali:/root/htb

  # kali2:
  #   image: kasmweb/core-kali-rolling:1.12.0
  #   container_name: kali-gui
  #   hostname: kali-gui
  #   privileged: true
  #   sysctls:
  #    - net.ipv6.conf.all.disable_ipv6=0
  #   user: 'root'
  #   tty: true
  #   shm_size: '512m'
  #   environment:
  #     VNC_PW: 'password'
  #   ports:
  #     - 6901:6901
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.250
  #   volumes: 
  #     - /Users/em0ral/lab/docker/kali:/root/htb

  # juice:
  #   image: bkimminich/juice-shop
  #   container_name: juice-shop
  #   ports:
  #     - 8080:3000
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.10

  # dvwa:
  #   image: vulnerables/web-dvwa
  #   container_name: dvwa
  #   ports:
  #     - 8081:80
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.20

  # webgoat:
  #   image: webgoat/webgoat
  #   container_name: webgoat
  #   ports:
  #     - 8082:8080
  #     - 9090-9090
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.30

networks:
  vulnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
          gateway: 10.20.0.1