### Vulnerable Web Network ###

version: '2.13.0'

services:

  kali:
    build: ./kali
    image: packethead/kali
    container_name: kali
    hostname: kali
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    tty: true
    networks:
      vulnet:
        ipv4_address: 10.20.0.200
    volumes: 
      - /Users/em0ral/lab/docker/kali/:/root/htb
      - ./kali/config/.tmux.conf:/root/.tmux.conf


  parrot:
    build: ./parrot
    image: packethead/parrot
    container_name: parrot
    hostname: parrot
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    tty: true
    networks:
      vulnet:
        ipv4_address: 10.20.0.220
    volumes: 
      - /Users/em0ral/lab/docker/parrot/:/root/htb
      - ./parrot/config/.tmux.conf:/root/.tmux.conf
  

  # kali2:
  #   image: kasmweb/core-kali-rolling:1.12.0
  #   container_name: kasm-kali
  #   hostname: kali
  #   privileged: true
  #   sysctls:
  #    - net.ipv6.conf.all.disable_ipv6=0
  #   user: 'root'
  #   tty: true
  #   shm_size: '512m'
  #   environment:
  #     VNC_PW: 'password'
  #   ports:
  #     - 6901:6901
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.100
  #   volumes: 
  #     - /Users/em0ral/lab/docker/kasm-kali:/home/kasm-user/htb

  # juice:
  #   image: bkimminich/juice-shop
  #   container_name: juice-shop
  #   ports:
  #     - 8080:3000
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.10

  # dvwa:
  #   image: vulnerables/web-dvwa
  #   container_name: dvwa
  #   ports:
  #     - 8081:80
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.20

  # webgoat:
  #   image: webgoat/webgoat
  #   container_name: webgoat
  #   ports:
  #     - 8082:8080
  #     - 9090-9090
  #   networks:
  #     vulnet:
  #       ipv4_address: 10.20.0.30

networks:
  vulnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
          gateway: 10.20.0.1